// This file is no longer used.
// UI is now dynamically generated by the AI orchestrator.
// Keeping as placeholder for any future static constants.

export const APP_NAME = "MomKidCare AI";
export const API_BASE = "http://localhost:3000/api";
